In [1]:
import numpy as np
import pandas as pd

tasks = pd.read_csv('tasks.csv')
tasks.head()

task_id  type product from loc to loc  time order     status
0        1  pick      p1       l1    l30    30    o1  available
1        2   put      p2      l31    l11    20   NaN  available
2        3  pick      p3       l3    l32    10    o2  available
3        4  pick      p4       l4    l30     5    o1  available
4        5  repl      p4       l5     l4     8    o1  available

In [2]:
# encode the df

# encode "type"
type_encoding = {
    "pick": 0,
    "put": 1,
    "load": 2,
    "repl": 3
}
tasks["type"] = tasks["type"].map(type_encoding)

tasks["product"] = tasks["product"].apply(lambda prod:  prod[1:]) # encode product
tasks["from loc"] = tasks["from loc"].apply(lambda loc:  loc[1:]) # encode from loc
tasks["to loc"] = tasks["to loc"].apply(lambda loc:  loc[1:]) # encode to loc

tasks.fillna({'order':'o0'}, inplace=True)  # encode to order
tasks["order"] = tasks["order"].apply(lambda order:  order[1:])


# encode status
status_encoding = {
    "available": 0,
    "active": 1,
    "done": 2,
}
tasks["status"] = tasks["status"].map(status_encoding)

task_list = tasks.to_numpy().tolist()
print(task_list)

tasks.head()



[[1, 0, '1', '1', '30', 30, '1', 0], [2, 1, '2', '31', '11', 20, '0', 0], [3, 0, '3', '3', '32', 10, '2', 0], [4, 0, '4', '4', '30', 5, '1', 0], [5, 3, '4', '5', '4', 8, '1', 0], [6, 0, '5', '6', '30', 10, '1', 0], [7, 3, '6', '7', '11', 11, '0', 0], [8, 0, '7', '8', '32', 14, '2', 0], [9, 2, '8', '30', '40', 9, '1', 0], [10, 2, '9', '32', '41', 10, '2', 0]]


task_id  type product from loc to loc  time order  status
0        1     0       1        1     30    30     1       0
1        2     1       2       31     11    20     0       0
2        3     0       3        3     32    10     2       0
3        4     0       4        4     30     5     1       0
4        5     3       4        5      4     8     1       0

In [3]:
devices = pd.read_csv('devices.csv')
# devices.head()

# type encodings
type_encodings = {
    "forklift": 0,
    "pallet_jack": 1
}
devices["type"] = devices["type"].map(type_encodings)

# encode status
status_encoding = {
    "available": 0,
    "active": 1,
}
devices["status"] = devices["status"].map(status_encoding)

device_list = devices.to_numpy().tolist()
print(device_list)

devices.head(10)

[[1, 0, 0], [2, 0, 0], [3, 0, 0], [4, 0, 0], [5, 1, 0], [6, 1, 0]]


device_id  type  status
0          1     0       0
1          2     0       0
2          3     0       0
3          4     0       0
4          5     1       0
5          6     1       0

In [4]:
from WarehouseEnv_V0 import WarehouseEnv

from stable_baselines3.common.env_checker import check_env

In [5]:
import gymnasium as gym

env = WarehouseEnv()

[encoding]: encoded task_list:  [[1, 0, 1, 1, 30, 30, 1, 0], [2, 1, 2, 31, 11, 20, 1, 0], [3, 0, 3, 3, 32, 10, 2, 0], [4, 0, 4, 4, 30, 5, 1, 0], [5, 3, 4, 5, 4, 8, 1, 0], [6, 0, 5, 6, 30, 10, 1, 0], [7, 3, 6, 7, 11, 11, 1, 0], [8, 0, 7, 8, 32, 14, 2, 0], [9, 2, 8, 30, 40, 9, 1, 0], [10, 2, 9, 32, 41, 10, 2, 0]]
[encoding]: encoded device_list:  [[1, 1, 0], [2, 1, 0], [3, 1, 0], [4, 1, 0], [5, 0, 0], [6, 0, 0]]


In [17]:
# print(task_list)
# print(env.observation_space['devices'])
# print(env.observation_space['tasks'])

tasks = env.observation_space['tasks']


next_state, reward = env.reset()

print("----")
print(next_state['tasks'])
tasks = next_state['tasks']


available_tasks = tasks[tasks[:, 7] == 0]
# env.action_space.n

[encoding]: encoded task_list:  [[1, 0, 1, 1, 30, 30, 1, 0], [2, 1, 2, 31, 11, 20, 1, 0], [3, 0, 3, 3, 32, 10, 2, 0], [4, 0, 4, 4, 30, 5, 1, 0], [5, 3, 4, 5, 4, 8, 1, 0], [6, 0, 5, 6, 30, 10, 1, 0], [7, 3, 6, 7, 11, 11, 1, 0], [8, 0, 7, 8, 32, 14, 2, 0], [9, 2, 8, 30, 40, 9, 1, 0], [10, 2, 9, 32, 41, 10, 2, 0]]
[encoding]: encoded device_list:  [[1, 1, 0], [2, 1, 0], [3, 1, 0], [4, 1, 0], [5, 0, 0], [6, 0, 0]]
----
[[ 1  0  1  1 30 30  1  0]
 [ 2  1  2 31 11 20  1  0]
 [ 3  0  3  3 32 10  2  0]
 [ 4  0  4  4 30  5  1  0]
 [ 5  3  4  5  4  8  1  0]
 [ 6  0  5  6 30 10  1  0]
 [ 7  3  6  7 11 11  1  0]
 [ 8  0  7  8 32 14  2  0]
 [ 9  2  8 30 40  9  1  0]
 [10  2  9 32 41 10  2  0]]


In [21]:
print(env.observation_space['devices'].shape)
env.action_space.n

(6, 3)


10

In [38]:
import random
(state,info) = env.reset()

tasks= state['tasks']

TASK_STATUS = 7
available_tasks = tasks[tasks[:, TASK_STATUS] == 0]
available_task_ids = [sublist[0] for sublist in available_tasks]

random_action = random.choice(available_task_ids)
print(random_action)

[encoding]: encoded task_list:  [[1, 0, 1, 1, 30, 30, 1, 0], [2, 1, 2, 31, 11, 20, 1, 0], [3, 0, 3, 3, 32, 10, 2, 0], [4, 0, 4, 4, 30, 5, 1, 0], [5, 3, 4, 5, 4, 8, 1, 0], [6, 0, 5, 6, 30, 10, 1, 0], [7, 3, 6, 7, 11, 11, 1, 0], [8, 0, 7, 8, 32, 14, 2, 0], [9, 2, 8, 30, 40, 9, 1, 0], [10, 2, 9, 32, 41, 10, 2, 0]]
[encoding]: encoded device_list:  [[1, 1, 0], [2, 1, 0], [3, 1, 0], [4, 1, 0], [5, 0, 0], [6, 0, 0]]
8


In [ ]:
env.sample()

{'tasks': array([[88,  1, 46, 88, 48, 52, 79,  1],
        [68,  3, 34, 31,  8, 30, 10,  2],
        [69,  1, 96, 65, 56, 42,  8,  2],
        [ 7,  1, 74, 65, 40, 19, 97,  2],
        [50,  3, 41, 12, 42, 58, 52,  1],
        [17,  2, 76, 19,  4, 22, 13,  1],
        [79,  2, 96, 23, 70, 16,  1,  1],
        [46,  0, 56, 95, 17, 52, 66,  0],
        [57,  3, 93, 38, 36, 49, 46,  0],
        [36,  0, 34, 87,  6, 38, 34,  0]]),
 'devices': array([[96,  1,  1],
        [79,  1,  0],
        [31,  1,  1],
        [67,  1,  1],
        [ 5,  1,  0],
        [85,  0,  0]])}

In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
agents = pd.read_csv('agents.csv') 

agents.head()

agent_id   type     status  reward  current_task  current_device
0         1  human  available       0            -1              -1

In [5]:
for index, agent in agents.iterrows():
    agent['status'] = 0
    agents.loc[index, 'reward'] = 10
    print(agent)

agents.head()

agent_id              1
type              human
status                0
reward                0
current_task         -1
current_device       -1
Name: 0, dtype: object


agent_id   type     status  reward  current_task  current_device
0         1  human  available      10            -1              -1